# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Destini-iOS13' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Destini-iOS13

  pod 'CLTypingLabel', '~> 0.4.0'
end
